version: '3'
services:
    postgres:
      environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=12345678
        - POSTGRES_MULTIPLE_DATABASES="starter-api","starter-api-testing"
      volumes:
        - ./docker-utils:/docker-entrypoint-initdb.d
        - starter_api_data:/data/postgres
      ports:
        - 5434:5432
volumes:
  starter_api_data: {}